remove hover message for closing function call parenthesis
julia-vscode/LanguageServer.jl pull request #967
Opened 2021-07-20 08:28 UTC by pfitzseb

because these are already indicated by highlighting the matching paren anyways.

2021-07-21 15:13 UTC, ZacLN commented
Happy for this to be removed but I think worth pointing out that I added this for the case where the opening paren isn't on the same page

2021-07-24 02:07 UTC, davidanthoff requested changes
Tests fail, and @pfitzseb do you think this should be merged in light of @ZacLN's comment?

2021-07-26 15:08 UTC, pfitzseb commented
Tests should pass now. And yes, in my opinion we should remove this; `Go To Bracket` almost provides the same functionality (imho it's more useful because you can also tell *which* `for` loop or whatever the current end closes). In addition, this makes inline results much nicer.

2021-07-26 16:17 UTC, davidanthoff approved these changes

2021-07-26 16:17 UTC, merged